module.exports = {
  REST: {
    BASE_URL: "https://discord.com/api",
    API_VERSION: 9
  },
  GATEWAY: {
    BASE_URL: "wss://gateway.discord.gg/",
    VERSION: 9
  },
  OP_CODES: {
    EVENT: 0,
    HEARTBEAT: 1,
    IDENTIFY: 2,
    STATUS_UPDATE: 3,
    VOICE_STATE_UPDATE: 4,
    VOICE_GUILD_PING: 5,
    RESUME: 6,
    RECONNECT: 7,
    REQUEST_GUILD_MEMBERS: 8,
    INVALID_SESSION: 9,
    HELLO: 10,
    HEARTBEAT_ACK: 11
  },
  INTENTS: {
    GUILDS:                   1 << 0,
    GUILD_MEMBERS:            1 << 1,
    GUILD_BANS:               1 << 2,
    GUILD_EMOJIS:             1 << 3,
    GUILD_INTEGRATIONS:       1 << 4,
    GUILD_WEBHOOKS:           1 << 5,
    GUILD_INVITES:            1 << 6,
    GUILD_VOICE_STATES:       1 << 7,
    GUILD_PRESENCES:          1 << 8,
    GUILD_MESSAGES:           1 << 9,
    GUILD_MESSAGE_REACTIONS:  1 << 10,
    GUILD_MESSAGE_TYPING:     1 << 11,
    DIRECT_MESSAGES:          1 << 12,
    DIRECT_MESSAGE_REACTIONS: 1 << 13,
    DIRECT_MESSAGE_TYPING:    1 << 14
  },
  ClientEvents: {
    READY: "ready",
    RESUMED: "resumed",
    GUILD_CREATE: "guildCreate",
    GUILD_DELETE: "guildDelete",
    GUILD_UPDATE: "guildUpdate",
    INVITE_CREATE: "inviteCreate",
    INVITE_DELETE: "inviteDelete",
    GUILD_MEMBER_ADD: "guildMemberAdd",
    GUILD_MEMBER_REMOVE: "guildMemberRemove",
    GUILD_MEMBER_UPDATE: "guildMemberUpdate",
    GUILD_MEMBERS_CHUNK: "guildMembersChunk",
    GUILD_INTEGRATIONS_UPDATE: "guildIntegrationsUpdate",
    GUILD_ROLE_CREATE: "guildRoleCreate",
    GUILD_ROLE_DELETE: "guildRoleDelete",
    GUILD_ROLE_UPDATE: "guildRoleUpdate",
    GUILD_BAN_ADD: "guildBanAdd",
    GUILD_BAN_REMOVE: "guildBanRemove",
    GUILD_EMOJIS_UPDATE: "guildEmojisUpdate",
    CHANNEL_CREATE: "channelCreate",
    CHANNEL_DELETE: "channelDelete",
    CHANNEL_UPDATE: "channelUpdate",
    CHANNEL_PINS_UPDATE: "channelPinsUpdate",
    MESSAGE_CREATE: "messageCreate",
    MESSAGE_DELETE: "messageDelete",
    MESSAGE_UPDATE: "messageUpdate",
    MESSAGE_DELETE_BULK: "messageDeleteBulk",
    MESSAGE_REACTION_ADD: "messageReactionAdd",
    MESSAGE_REACTION_REMOVE: "messageReactionRemove",
    MESSAGE_REACTION_REMOVE_ALL: "messageReactionRemoveAll",
    MESSAGE_REACTION_REMOVE_EMOJI: "messageReactionRemoveEmoji",
    THREAD_CREATE: "threadCreate",
    THREAD_UPDATE: "threadUpdate",
    THREAD_DELETE: "threadDelete",
    THREAD_LIST_SYNC: "threadListSync",
    THREAD_MEMBER_UPDATE: "threadMemberUpdate",
    THREAD_MEMBERS_UPDATE: "threadMembersUpdate",
    USER_UPDATE: "userUpdate",
    PRESENCE_UPDATE: "presenceUpdate",
    TYPING_START: "typingStart",
    VOICE_STATE_UPDATE: "voiceStateUpdate",
    VOICE_SERVER_UPDATE: "voiceServerUpdate",
    WEBHOOKS_UPDATE: "webhooksUpdate",
    INTERACTION_CREATE: "interactionCreate",
    STAGE_INSTANCE_CREATE: "stageInstanceCreate",
    STAGE_INSTANCE_UPDATE: "stageInstanceUpdate",
    STAGE_INSTANCE_DELETE: "stageInstanceDelete"
  },
  ChannelTypes: {
    GUILD_TEXT: 0,
    DM: 1,
    GUILD_VOICE: 2,
    GROUP_DM: 3,
    GUILD_CATEGORY: 4,
    GUILD_NEWS: 5,
    GUILD_STORE: 6,
    GUILD_NEWS_THREAD: 10,
    GUILD_PUBLIC_THREAD: 11,
    GUILD_PRIVATE_THREAD: 12,
    GUILD_STAGE_VOICE: 13
  },
  MessageComponentTypes: {
    ACTION_ROW: 1,
    BUTTON: 2,
    SELECT_MENU: 3
  },
  InteractionTypes: {
    PING: 1,
    APPLICATION_COMMAND: 2,
    MESSAGE_COMPONENT: 3
  },
  InteractionResponseTypes: {
    PONG: 1,
    CHANNEL_MESSAGE_WITH_SOURCE: 4,
    DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE: 5,
    DEFERRED_UPDATE_MESSAGE: 6,
    UPDATE_MESSAGE: 7
  },
  CommandTypes: {
    CHAT_INPUT: 1,
    USER: 2,
    MESSAGE: 3
  },
  CommandOptionTypes: {
    SUB_COMMAND: 1,
    SUB_COMMAND_GROUP: 2,
    STRING:	3,
    INTEGER: 4,
    BOOLEAN: 5,
    USER:	6,
    CHANNEL:7,
    ROLE:	8,
    MENTIONABLE:9,
    NUMBER:	10
  },
  GatewayErrors: {
    UNKNOWN: 4000,
    UNKNOWN_OPCODE: 4001,
    DECODE_ERROR: 4002,
    NOT_AUTHENTICATED: 4003,
    AUTHENTICATION_FAILED: 4004,
    ALREADY_AUTHENTICATED: 4005,
    INVALID_SEQUENCE: 4007,
    RATE_LIMITED: 4008,
    TIMED_OUT: 4009,
    INVALID_SHARD: 4010,
    SHARDING_REQUIRED: 4011,
    INVALID_API_VERSION: 4012,
    INVALID_INTENT: 4013,
    DISALLOWED_INTENT: 4014
  },
  ImageFormats: ["webp", "png", "jpg", "jpeg", "gif"],
  ImageSizes: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
};
