module.exports = {
  CHANNEL =                                                (chanID) => `/channels/${chanID}`,
  CHANNEL_BULK_DELETE =                                    (chanID) => `/channels/${chanID}/messages/bulk-delete`,
  CHANNEL_CALL_RING =                                      (chanID) => `/channels/${chanID}/call/ring`,
  CHANNEL_CROSSPOST =                               (chanID, msgID) => `/channels/${chanID}/messages/${msgID}/crosspost`,
  CHANNEL_FOLLOW =                                         (chanID) => `/channels/${chanID}/followers`,
  CHANNEL_INVITES =                                        (chanID) => `/channels/${chanID}/invites`,
  CHANNEL_MESSAGE_REACTION =              (chanID, msgID, reaction) => `/channels/${chanID}/messages/${msgID}/reactions/${reaction}`,
  CHANNEL_MESSAGE_REACTION_USER = (chanID, msgID, reaction, userID) => `/channels/${chanID}/messages/${msgID}/reactions/${reaction}/${userID}`,
  CHANNEL_MESSAGE_REACTIONS =                       (chanID, msgID) => `/channels/${chanID}/messages/${msgID}/reactions`,
  CHANNEL_MESSAGE =                                 (chanID, msgID) => `/channels/${chanID}/messages/${msgID}`,
  CHANNEL_MESSAGES =                                       (chanID) => `/channels/${chanID}/messages`,
  CHANNEL_MESSAGES_SEARCH =                                (chanID) => `/channels/${chanID}/messages/search`,
  CHANNEL_PERMISSION =                             (chanID, overID) => `/channels/${chanID}/permissions/${overID}`,
  CHANNEL_PERMISSIONS =                                    (chanID) => `/channels/${chanID}/permissions`,
  CHANNEL_PIN =                                     (chanID, msgID) => `/channels/${chanID}/pins/${msgID}`,
  CHANNEL_PINS =                                           (chanID) => `/channels/${chanID}/pins`,
  CHANNEL_RECIPIENT =                             (groupID, userID) => `/channels/${groupID}/recipients/${userID}`,
  CHANNEL_TYPING =                                         (chanID) => `/channels/${chanID}/typing`,
  CHANNEL_WEBHOOKS =                                       (chanID) => `/channels/${chanID}/webhooks`,
  CHANNELS =                                                           "/channels",
  CUSTOM_EMOJI_GUILD =                                    (emojiID) => `/emojis/${emojiID}/guild`,
  DISCOVERY_CATEGORIES =                                               "/discovery/categories",
  DISCOVERY_VALIDATION =                                               "/discovery/valid-term",
  GATEWAY =                                                            "/gateway",
  GATEWAY_BOT =                                                        "/gateway/bot",
  GUILD =                                                 (guildID) => `/guilds/${guildID}`,
  GUILD_AUDIT_LOGS =                                      (guildID) => `/guilds/${guildID}/audit-logs`,
  GUILD_BAN =                                   (guildID, memberID) => `/guilds/${guildID}/bans/${memberID}`,
  GUILD_BANS =                                            (guildID) => `/guilds/${guildID}/bans`,
  GUILD_CHANNELS =                                        (guildID) => `/guilds/${guildID}/channels`,
  GUILD_DISCOVERY =                                       (guildID) => `/guilds/${guildID}/discovery-metadata`,
  GUILD_DISCOVERY_CATEGORY =                  (guildID, categoryID) => `/guilds/${guildID}/discovery-categories/${categoryID}`,
  GUILD_EMBED =                                           (guildID) => `/guilds/${guildID}/embed`,
  GUILD_EMOJI =                                  (guildID, emojiID) => `/guilds/${guildID}/emojis/${emojiID}`,
  GUILD_EMOJIS =                                          (guildID) => `/guilds/${guildID}/emojis`,
  GUILD_INTEGRATION =                             (guildID, inteID) => `/guilds/${guildID}/integrations/${inteID}`,
  GUILD_INTEGRATION_SYNC =                        (guildID, inteID) => `/guilds/${guildID}/integrations/${inteID}/sync`,
  GUILD_INTEGRATIONS =                                    (guildID) => `/guilds/${guildID}/integrations`,
  GUILD_INVITES =                                         (guildID) => `/guilds/${guildID}/invites`,
  GUILD_VANITY_URL =                                      (guildID) => `/guilds/${guildID}/vanity-url`,
  GUILD_MEMBER =                                (guildID, memberID) => `/guilds/${guildID}/members/${memberID}`,
  GUILD_MEMBER_NICK =                           (guildID, memberID) => `/guilds/${guildID}/members/${memberID}/nick`,
  GUILD_MEMBER_ROLE =                   (guildID, memberID, roleID) => `/guilds/${guildID}/members/${memberID}/roles/${roleID}`,
  GUILD_MEMBERS =                                         (guildID) => `/guilds/${guildID}/members`,
  GUILD_MEMBERS_SEARCH =                                  (guildID) => `/guilds/${guildID}/members/search`,
  GUILD_MESSAGES_SEARCH =                                 (guildID) => `/guilds/${guildID}/messages/search`,
  GUILD_PREVIEW =                                         (guildID) => `/guilds/${guildID}/preview`,
  GUILD_PRUNE =                                           (guildID) => `/guilds/${guildID}/prune`,
  GUILD_ROLE =                                    (guildID, roleID) => `/guilds/${guildID}/roles/${roleID}`,
  GUILD_ROLES =                                           (guildID) => `/guilds/${guildID}/roles`,
  GUILD_TEMPLATE =                                           (code) => `/guilds/template/${code}`,
  GUILD_TEMPLATES =                                       (guildID) => `/guilds/${guildID}/templates`,
  GUILD_TEMPLATE_GUILD =                            (guildID, code) => `/guilds/${guildID}/templates/${code}`,
  GUILD_VOICE_REGIONS =                                   (guildID) => `/guilds/${guildID}/regions`,
  GUILD_WEBHOOKS =                                        (guildID) => `/guilds/${guildID}/webhooks`,
  GUILD_WELCOME_SCREEN =                                  (guildID) => `/guilds/${guildID}/welcome-screen`,
  GUILD_WIDGET =                                          (guildID) => `/guilds/${guildID}/widget`,
  GUILD_VOICE_STATE =                               (guildID, user) => `/guilds/${guildID}/voice-states/${user}`,
  GUILDS =                                                             "/guilds",
  INVITE =                                               (inviteID) => `/invite/${inviteID}`,
  OAUTH2_APPLICATION =                                      (appID) => `/oauth2/applications/${appID}`,
  USER =                                                   (userID) => `/users/${userID}`,
  USER_BILLING =                                           (userID) => `/users/${userID}/billing`,
  USER_BILLING_PAYMENTS =                                  (userID) => `/users/${userID}/billing/payments`,
  USER_BILLING_PREMIUM_SUBSCRIPTION =                      (userID) => `/users/${userID}/billing/premium-subscription`,
  USER_CHANNELS =                                          (userID) => `/users/${userID}/channels`,
  USER_CONNECTIONS =                                       (userID) => `/users/${userID}/connections`,
  USER_CONNECTION_PLATFORM =                 (userID, platform, id) => `/users/${userID}/connections/${platform}/${id}`,
  USER_GUILD =                                    (userID, guildID) => `/users/${userID}/guilds/${guildID}`,
  USER_GUILDS =                                            (userID) => `/users/${userID}/guilds`,
  USER_MFA_CODES =                                         (userID) => `/users/${userID}/mfa/codes`,
  USER_MFA_TOTP_DISABLE =                                  (userID) => `/users/${userID}/mfa/totp/disable`,
  USER_MFA_TOTP_ENABLE =                                   (userID) => `/users/${userID}/mfa/totp/enable`,
  USER_NOTE =                                    (userID, targetID) => `/users/${userID}/note/${targetID}`,
  USER_PROFILE =                                           (userID) => `/users/${userID}/profile`,
  USER_RELATIONSHIP =                               (userID, relID) => `/users/${userID}/relationships/${relID}`,
  USER_SETTINGS =                                          (userID) => `/users/${userID}/settings`,
  USERS =                                                              "/users",
  VOICE_REGIONS =                                                      "/voice/regions",
  WEBHOOK =                                                (hookID) => `/webhooks/${hookID}`,
  WEBHOOK_MESSAGE =                          (hookID, token, msgID) => `/webhooks/${hookID}/${token}/messages/${msgID}`,
  WEBHOOK_SLACK =                                          (hookID) => `/webhooks/${hookID}/slack`,
  WEBHOOK_TOKEN =                                   (hookID, token) => `/webhooks/${hookID}/${token}`,
  WEBHOOK_TOKEN_SLACK =                             (hookID, token) => `/webhooks/${hookID}/${token}/slack`,
  
  // CDN Endpoints
  ACHIEVEMENT_ICON =           (applicationID, achievementID, icon) => `/app-assets/${applicationID}/achievements/${achievementID}/icons/${icon}`,
  APPLICATION_ASSET =                        (applicationID, asset) => `/app-assets/${applicationID}/${asset}`,
  APPLICATION_ICON =                          (applicationID, icon) => `/app-icons/${applicationID}/${icon}`,
  CHANNEL_ICON =                                 (chanID, chanIcon) => `/channel-icons/${chanID}/${chanIcon}`,
  CUSTOM_EMOJI =                                          (emojiID) => `/emojis/${emojiID}`,
  DEFAULT_USER_AVATAR =                         (userDiscriminator) => `/embed/avatars/${userDiscriminator}`,
  GUILD_BANNER =                             (guildID, guildBanner) => `/banners/${guildID}/${guildBanner}`,
  GUILD_DISCOVERY_SPLASH =          (guildID, guildDiscoverySplash) => `/discovery-splashes/${guildID}/${guildDiscoverySplash}`,
  GUILD_ICON =                                 (guildID, guildIcon) => `/icons/${guildID}/${guildIcon}`,
  GUILD_SPLASH =                             (guildID, guildSplash) => `/splashes/${guildID}/${guildSplash}`,
  TEAM_ICON                                    = (teamID, teamIcon) => `/team-icons/${teamID}/${teamIcon}`,
  USER_AVATAR =                                (userID, userAvatar) => `/avatars/${userID}/${userAvatar}`,
  
  // Client Endpoints
  MESSAGE_LINK =                    (guildID, channelID, messageID) => `/channels/${guildID}/${channelID}/${messageID}`
};